### ISSUE TITLE
[Bug?] error in setting torch_dtype

### ISSUE THREAD

**Issue by LEON-REIN** [LagPixelLOL/qlora#1]
Are these two leading `torch.float32` typos? 
>https://github.com/LagPixelLOL/qlora/blob/89d3cb9d20c963d78063031f5214c878e9512786/qlora.py#L327
>https://github.com/LagPixelLOL/qlora/blob/89d3cb9d20c963d78063031f5214c878e9512786/qlora.py#L344

**Comment by LagPixelLOL** [comment]
heh... idk
im not the owner of this project, i just forked it for personal use...
i didnt modify qlora.py iirc
i think you should report this to upstream
